CREATE TABLE DWBA.REGISTRO_CLICKTOPAY
(
	ID_REGISTRO int IDENTITY(1,1) NOT NULL,
	UNICO decimal(15,0) NOT NULL,
	PAN varchar(16) NOT NULL,
	NOMBRE varchar(100) NOT NULL,
	EMAIL nvarchar(60) NOT NULL,
	TELEFONO nvarchar(20) NOT NULL,
	DIRECCION nvarchar(150) NOT NULL,
	ESTATUS varchar(50)  NOT NULL,
	FECHAHORA datetime NOT NULL,
	
	CONSTRAINT PK_REGISTRO_CLICKTOPAY PRIMARY KEY (ID_REGISTRO)
);