-- DROP TABLE DWBA.BULK_STATUS_CTP;

CREATE TABLE DWBA.BULK_STATUS_CTP
(
	ID_REGISTRO int IDENTITY(1,1) NOT NULL,
	BULKRECEIPTID varchar(50) NOT NULL,
	BULK_STATUS varchar(50) NOT NULL,
	FECHAHORA datetime NOT NULL
	
	CONSTRAINT PK_BULK_STATUS_CTP PRIMARY KEY (ID_REGISTRO)
);